# Generated by Django 5.0.7 on 2025-02-16 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('canal_captacion', models.CharField(blank=True, max_length=100, null=True)),
                ('ultima_clase', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FacturaPago',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('identificador', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id_instructor', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id_paquete', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_clases', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoPaquete',
            fields=[
                ('id_alumno_paquete', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('expirado', 'Expirado')], max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilapp.alumno')),
                ('id_paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilapp.paquete')),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoClase',
            fields=[
                ('id_alumno_clase', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('asistió', 'Asistió'), ('faltó', 'Faltó'), ('canceló', 'Canceló'), ('recuperó', 'Recuperó')], max_length=50)),
                ('id_alumno_paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilapp.alumnopaquete')),
                ('id_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilapp.clase')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='id_instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilapp.instructor'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nro_pago', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], max_length=50)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=50)),
                ('comprobante', models.CharField(blank=True, max_length=100, null=True)),
                ('id_factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pilapp.facturapago')),
            ],
        ),
        migrations.AddField(
            model_name='facturapago',
            name='id_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilapp.pago'),
        ),
        migrations.CreateModel(
            name='PagoAlumno',
            fields=[
                ('id_pago_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_alumno_paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilapp.alumnopaquete')),
                ('id_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilapp.pago')),
            ],
        ),
        migrations.CreateModel(
            name='PagoInstructor',
            fields=[
                ('id_pago_instructor', models.AutoField(primary_key=True, serialize=False)),
                ('id_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilapp.instructor')),
                ('id_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilapp.pago')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilapp.persona'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilapp.persona'),
        ),
        migrations.AddField(
            model_name='clase',
            name='id_turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilapp.turno'),
        ),
    ]
