# Generated by Django 6.0.1 on 2026-06-16 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelacionAlumno',
            fields=[
                ('id_relacion_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_relacion', models.CharField(choices=[('familiares', 'Familiares'), ('amigos', 'Amigos'), ('pareja', 'Pareja'), ('otro', 'Otro')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('id_alumno_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_como_alumno_1', to='Pilapp.alumno')),
                ('id_alumno_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_como_alumno_2', to='Pilapp.alumno')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id_alumno_1', models.F('id_alumno_2')), _negated=True), name='evitar_autorelacion_alumno'), models.UniqueConstraint(fields=('id_alumno_1', 'id_alumno_2'), name='unique_par_alumnos')],
            },
        ),
    ]
