# Generated by Django 5.0.7 on 2025-02-16 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pilapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='fecha',
        ),
    ]
