# Generated by Django 5.0.7 on 2026-07-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilapp', '0002_feriado_relacionalumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnoclase',
            name='estado',
            field=models.CharField(choices=[('asistió', 'Asistió'), ('faltó', 'Faltó'), ('canceló', 'Canceló'), ('recuperó', 'Recuperó'), ('reprogramó', 'Reprogramó'), ('pendiente', 'Pendiente'), ('feriado', 'Feriado')], max_length=50),
        ),
    ]
