# Generated by Django 5.0.7 on 2025-02-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilapp', '0002_remove_instructor_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
