# Generated by Django 5.0.7 on 2026-07-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilapp', '0003_alter_alumnoclase_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='razon_social',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
