# Generated by Django 5.0.7 on 2025-02-16 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilapp', '0003_turno_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnopaquete',
            name='fecha_fin',
        ),
        migrations.AlterField(
            model_name='alumnopaquete',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='AlumnoPaqueteTurno',
            fields=[
                ('id_alumno_paquete_turno', models.AutoField(primary_key=True, serialize=False)),
                ('id_alumno_paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilapp.alumnopaquete')),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilapp.turno')),
            ],
        ),
    ]
