# Generated by Django 5.0.7 on 2026-07-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilapp', '0004_persona_razon_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='disciplina',
            field=models.CharField(choices=[('Reformer', 'Reformer'), ('MAT', 'MAT')], default='Reformer', max_length=50),
        ),
        migrations.AlterField(
            model_name='turno',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado')], max_length=20),
        ),
    ]
