# Generated by Django 5.0.7 on 2025-02-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilapp', '0004_remove_alumnopaquete_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Ocupado', 'Ocupado')], default='Libre', max_length=10),
        ),
    ]
