# Generated by Django 5.0.7 on 2026-07-06 01:59

from django.db import migrations
import datetime

def create_mat_turnos(apps, schema_editor):
    Turno = apps.get_model('Pilapp', 'Turno')
    
    # Crear turnos MAT Martes y Jueves 18:30 y 19:30
    turnos_data = [
        ('Martes', datetime.time(18, 30)),
        ('Martes', datetime.time(19, 30)),
        ('Jueves', datetime.time(18, 30)),
        ('Jueves', datetime.time(19, 30)),
    ]
    
    for dia, horario in turnos_data:
        Turno.objects.get_or_create(
            dia=dia, 
            horario=horario, 
            disciplina='MAT'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('Pilapp', '0005_turno_disciplina'),
    ]

    operations = [
        migrations.RunPython(create_mat_turnos),
    ]
