# Generated by Django 5.0.7 on 2025-02-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilapp', '0005_turno_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='lugares_ocupados',
            field=models.IntegerField(default=0),
        ),
    ]
