# Generated by Django 5.0.7 on 2026-07-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilapp', '0006_create_mat_turnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReemplazoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha habilitada')),
            ],
            options={
                'verbose_name': 'Día de Reemplazo',
                'verbose_name_plural': 'Días de Reemplazo',
            },
        ),
    ]
