# Generated by Django 5.0.7 on 2025-02-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilapp', '0006_turno_lugares_ocupados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnoclase',
            name='estado',
            field=models.CharField(choices=[('asistió', 'Asistió'), ('faltó', 'Faltó'), ('canceló', 'Canceló'), ('recuperó', 'Recuperó'), ('reprogramó', 'Reprogramó')], max_length=50),
        ),
    ]
