# Generated by Django 5.0.7 on 2026-07-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilapp', '0007_reemplazodia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExAlumno',
            fields=[
                ('id_ex_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('horarios', models.TextField(blank=True, help_text='Turnos que tenía asignados', null=True)),
                ('fecha_baja', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
