# Generated by Django 5.0.7 on 2025-02-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilapp', '0007_alter_alumnoclase_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnoclase',
            name='estado',
            field=models.CharField(choices=[('asistió', 'Asistió'), ('faltó', 'Faltó'), ('canceló', 'Canceló'), ('recuperó', 'Recuperó'), ('reprogramó', 'Reprogramó'), ('pendiente', 'Pendiente')], max_length=50),
        ),
    ]
