# Generated by Django 5.0.7 on 2025-03-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilapp', '0008_alter_alumnoclase_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='MenuPrincipal', max_length=50)),
                ('paso', models.IntegerField(default=0)),
                ('datos', models.JSONField(default=dict)),
            ],
        ),
    ]
