# Generated by Django 5.0.7 on 2026-08-03 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilapp', '0008_exalumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoalumno',
            name='id_alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pilapp.alumno'),
        ),
        migrations.AlterField(
            model_name='pagoalumno',
            name='id_alumno_paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pilapp.alumnopaquete'),
        ),
    ]
