# Generated by Django 5.0.7 on 2026-08-11 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilapp', '0009_pagoalumno_id_alumno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HonorarioInstructor',
            fields=[
                ('id_honorario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('turno', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Otro', 'Otro')], max_length=10)),
                ('cantidad_clases', models.IntegerField(default=1)),
                ('monto_total', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilapp.instructor')),
            ],
        ),
    ]
