# Generated by Django 5.0.7 on 2025-03-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilapp', '0009_conversacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='fecha',
            field=models.DateField(),
        ),
    ]
