# Generated by Django 5.0.7 on 2025-04-27 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilapp', '0012_alter_turno_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteProspecto',
            fields=[
                ('id_prospecto', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_contacto', models.DateField(auto_now_add=True)),
                ('canal_captacion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('interesado', 'Interesado'), ('contactado', 'Contactado'), ('no_interesado', 'No Interesado')], max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='estado',
            field=models.CharField(choices=[('ocasional', 'Ocasional'), ('regular', 'Regular'), ('inactivo', 'Inactivo')], default='ocasional', max_length=50),
        ),
        migrations.AddField(
            model_name='alumnopaquete',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Pago Parcial')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('rechazado', 'Rechazado'), ('parcial', 'Pago Parcial')], max_length=50),
        ),
        migrations.CreateModel(
            name='AlumnoClaseOcasional',
            fields=[
                ('id_alumno_clase_ocasional', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('asistió', 'Asistió'), ('faltó', 'Faltó'), ('canceló', 'Canceló')], max_length=50)),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilapp.alumno')),
                ('id_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilapp.clase')),
            ],
            options={
                'unique_together': {('id_alumno', 'id_clase')},
            },
        ),
    ]
