# Generated by Django 5.0.7 on 2025-04-27 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pilapp', '0013_clienteprospecto_alumno_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='lugares_ocupados',
        ),
    ]
