# Generated by Django 5.0.7 on 2026-03-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilapp', '0014_remove_turno_estado_remove_turno_lugares_ocupados'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='total_inscriptos',
            field=models.IntegerField(default=0),
        ),
    ]
