# Generated by Django 5.0.7 on 2026-03-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilapp', '0015_clase_total_inscriptos'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnopaquete',
            name='clases_usadas',
            field=models.IntegerField(default=0),
        ),
    ]
